# Generated by Django 5.0 on 2024-01-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_rename_category_name_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='posts', through='News.PostCategory', to='News.category'),
        ),
    ]
